query getBranchNear($shopId: ID!, $point: UpdateGeoPointInput!) {
  metaddress(shopId: $shopId, point: $point) {
    administrative_area_level_1
    administrative_area_level_2
    neighborhood
    street_address
    sublocality
    distance {
      text
      value
      branchId
      branch
    }
  }
}

mutation updateMetadataAddressBook(
  $metaddress: MetaddressInput
  $addressId: ID
) {
  updateMetadataAddressBook(metaddress: $metaddress, addressId: $addressId) {
    _id
    description
    address
    reference
    receiver
    phone
    geolocation {
      latitude
      longitude
    }
    metaddress {
      administrative_area_level_1
      administrative_area_level_2
      neighborhood
      street_address
      sublocality
      distance {
        text
        value
        branchId
        branch
      }
    }
  }
}
