#import "./fragments.gql"

# place an order
mutation placeOrderMutation($input: PlaceOrderInput!, $language: String! = "en") {
  cOrder(input: $input) {
    orders {
      ...OrderQueryFragment
    },
    token
  }
}
