mutation addAccountAddressBookEntryMutation(
  $input: AddAccountAddressBookEntryInput!
) {
  addAccountAddressBookEntry(input: $input) {
    address {
      _id
      address1
      metafields {
        description
        key
        namespace
        scope
        value
        valueType
      } 
    }
  }
}

mutation updateAccountAddressBookEntryMutation(
  $input: UpdateAccountAddressBookEntryInput!
) {
  updateAccountAddressBookEntry(input: $input) {
    address {
      _id
      address1
      metafields {
        description
        key
        namespace
        scope
        value
        valueType
      }
    }
  }
}

mutation removeAccountAddressBookEntryMutation(
  $input: RemoveAccountAddressBookEntryInput!
) {
  removeAccountAddressBookEntry(input: $input) {
    address {
      _id
      address1
      metafields {
        description
        key
        namespace
        scope
        value
        valueType
      } 
    }
  }
}
