mutation addAccountAddressBookEntryMutation($input: AddAccountAddressBookEntryInput!) {
  addAccountAddressBookEntry(input: $input) {
    address {
      _id
      description
      address
      reference
      phone
      receiver
      geolocation{
        latitude
        longitude
      }
      metaddress{
        administrative_area_level_1
        administrative_area_level_2
        neighborhood
        street_address
        sublocality
        distance{
          value
          text
          branch
          branchId
        }
      }
    }
  }
}

mutation updateAccountAddressBookEntryMutation($input: UpdateAccountAddressBookEntryInput!) {
  updateAccountAddressBookEntry(input: $input) {
    address {
      _id
      description
      address
      reference
      phone
      receiver
      geolocation{
        latitude
        longitude
      }
      metaddress{
        administrative_area_level_1
        administrative_area_level_2
        neighborhood
        street_address
        sublocality
        distance{
          value
          text
          branch
          branchId
        }
      }
    }
  }
}

mutation removeAccountAddressBookEntryMutation($input: RemoveAccountAddressBookEntryInput!) {
  removeAccountAddressBookEntry(input: $input) {
    address {
      _id
      description
      address
      reference
      receiver
      phone
      geolocation{
        latitude
        longitude
      }
      metaddress{
        administrative_area_level_1
        administrative_area_level_2
        neighborhood
        street_address
        sublocality
        distance{
          value
          text
          branch
          branchId
        }
      }
    }
  }
}

mutation uAccountAddress($input: UpdateAccountAddressInput!) {
  uAccountAddress(input: $input) {
    address {
      _id
      isDef
      address1
      address2
      city
      company
      country
      fullName
      isBillingDefault
      isCommercial
      isShippingDefault
      phone
      postal
      region
    }
  }
}