query viewer {
  viewer {
    _id
    userId
    addressBook {
      edges {
        node {
          _id
          description
          address
          reference
          receiver
          phone
          geolocation {
            latitude
            longitude
          }
          metaddress {
            administrative_area_level_1
            administrative_area_level_2
            neighborhood
            street_address
            sublocality
            distance {
              value
              text
              branchId
              branch
            }
          }
        }
      }
    }
    emailRecords {
      address
    }
    phone
    username
    name
    primaryEmailAddress
  }
}
